### PR TITLE
Fixed MECH and INDU sequences

### LINKED ISSUE #39: Very weird style for MECH/INDU recommended sequences
I want your guys opinion on what the resulting JSON should look for the following:

([INDU-Coop](https://www.concordia.ca/encs/mechanical-industrial/students/undergraduate/course-sequences/co-op-indu.html))
image

In english words, this page is saying that 

- you must take `INDU 421` and `INDU 423` in the fall of year 4
- you must take `INDU 321` and `INDU 342` in the winter of year 4
- you must take 17.75 credits of technical electives between fall & winter of year 4
- you must take the course `INDU 490` in BOTH the fall and winter of year 4

It may be worth noting that there are other sequences that include a course that spans over two semesters like `INDU 490` does, in which case the current scraper plainly adds this course to both of the two semesters in question (the website also lists the course in both the semesters instead of this stupidity of putting ANDs and ORs in the semester season header)

To re-iterate, I want to know what you guys think the resulting json should look like for these fall and winter semesters. Currently, the scraper poops the bed and does something like this:

```json
{
    "season": "fall",
    "courseList": [
        {
            "code": "INDU 421",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "INDU 423",
            "isElective": "false",
            "electiveType": ""
        }
    ],
    "isWorkTerm": "false"
},
{
    "season": "winter",
    "courseList": [
        {
            "code": "INDU 321",
            "isElective": "false",
            "electiveType": ""
        },
        {
            "code": "INDU 342",
            "isElective": "false",
            "electiveType": ""
        }
    ],
    "isWorkTerm": "false"
},
{
    "season": "fall",
    "courseList": [
        {
            "code": "INDU 490",
            "isElective": "false",
            "electiveType": ""
        }
    ],
    "isWorkTerm": "false"
}
```

### PR DESCRIPTION
**Pull request by Davidster**
resolves #39 
## Summary
The sequence scraper has been fixed to follow the format discussed in the comments section of the issue in question for MECH and INDU sequences. At this point, there are no real discrepancies between any of the sequences we currently support and the output of our sequence scraper, so the document `PerfectionChecklist.txt` has been removed.
## Example
Below is a sample of comparing the input (concordia site) to the new user-readable output (in the frontend).
Input:
image
Output:
image

### CODE REVIEW

**Comment by Davidster** [comment]
There's nothing on the Concordia site saying that you **must** follow any of these recommended sequences. They're simply recommended. Therefore we should definitely **allow** the user to drag those technical electives elsewhere in the sequence at their own (in)convenience

**Comment by stumash** [comment]
@PeterGhimself , we shouldn't be thinking about non-essential features until the MVC is done.

**Comment by Davidster** [comment]
Minimum Viable Compooperprogram

**Comment by PeterGhimself** [comment]
@stumash I'm going to be implementing dragging and dropping so I thought it was a fair question to ask on my part

**Comment by stumash** [comment]
special drag and drop restrictions have nothing to do with the initial implementation of drag and drop

**Pull request merged**
