### PR TITLE
Style changes

### PR DESCRIPTION
**Pull request by PeterGhimself**

### CODE REVIEW

**Comment by Davidster** [comment]
The export button is translucent but the search button isnt.. I think they should be the same.. my vote is for non-translucent buttons

**Comment by PeterGhimself** [comment]
Yeah I was actually trying to go for that at first but it wasn't working lol

**Comment by PeterGhimself** [comment]
And btw the search button is actually translucent, look a little closer

**Comment by Davidster** [comment]
ight yea its fine just merge it then

**Pull request merged**
